### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by ikalininskiy** [vodolaz095/static-yandex-map#2]
I get this url:
http://static-maps.yandex.ru/1.x/?ll=62.045122,129.743667&z=16&l=map&size=640,400&pt=62.045122,129.743667,pm2rdl

with this code:
        var s = new stym(msg.location.latitude, msg.location.longitude)
            .setType('map')
            .setSize(650,450)
            .setZ(13)
            .setLang('ru-RU')
            .addPoint(msg.location.latitude, msg.location.longitude, 'pm2', 'gn', 'm', 1);
            
        console.log(s.getUrl());    

but I have this error:
<error>
<status>400</status>
<message>ll parameter malformed</message>
</error>

but coordinates correct and work fine - I check it on http://www.gps-coordinates.net/

Help please, why I have this strange error

**Comment by vodolaz095** [comment]
imho you misplaced latitude and longiture

your link gives 
```
<error><status>400</status><message>ll parameter malformed</message></error>
```
try code

```js

var s = new stym(msg.location.longitude, msg.location.latitude)
.setType('map')
.setSize(650,450)
.setZ(13)
.setLang('ru-RU')
.addPoint(msg.location.longitude, msg.location.latitude, 'pm2', 'gn', 'm', 1);

```
It gives me this link

http://static-maps.yandex.ru/1.x/?ll=129.743667,62.045122&z=16&l=map&size=640,400&pt=129.743667,62.045122,pm2rdl



Which shows image
![http://static-maps.yandex.ru/1.x/?ll=129.743667,62.045122&z=16&l=map&size=640,400&pt=129.743667,62.045122,pm2rdl](http://static-maps.yandex.ru/1.x/?ll=129.743667,62.045122&z=16&l=map&size=640,400&pt=129.743667,62.045122,pm2rdl)
